name: Build Android (GitHub CI)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-levels: 33
          components: 'platform-tools,build-tools;33.0.2,platforms;android-33'

      - name: Make gradlew executable if present
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Ensure settings.gradle exists
        run: |
          if [ ! -f settings.gradle ] && [ ! -f settings.gradle.kts ]; then
            cat > settings.gradle <<'SET'
pluginManagement {
  repositories {
    gradlePluginPortal()
    google()
    mavenCentral()
  }
}
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
  }
}
rootProject.name = 'lsposed_build_project'
SET
          fi

      - name: Create gradle wrapper if missing (CI fallback)
        run: |
          if [ ! -f ./gradlew ]; then
            sudo apt-get update -y
            sudo apt-get install -y unzip wget zip
            wget https://services.gradle.org/distributions/gradle-9.0-bin.zip -O gradle-9.0-bin.zip
            unzip -qq gradle-9.0-bin.zip -d /opt
            export PATH=/opt/gradle-9.0/bin:$PATH
            gradle wrapper
            chmod +x ./gradlew
          fi

      - name: Build (assembleDebug for CI test)
        run: |
          set -e
          if [ -f ./gradlew ]; then
            ./gradlew --no-daemon --stacktrace clean assembleDebug
          else
            gradle --no-daemon --stacktrace clean assembleDebug
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/aar/*.aar
